import { DepartmentTemplate } from '../types';

export const ophthalmologyTemplate: DepartmentTemplate = {
  departmentKey: 'ophthalmology',
  departmentName: '안과',
  departmentNameEn: 'Ophthalmology',
  version: '1.0.0',

  sections: [
    { key: 'history', title: '병력', titleEn: 'History', order: 1 },
    { key: 'examination', title: '안과 검사', titleEn: 'Ophthalmic Examination', order: 2 },
    { key: 'diagnosis', title: '진단', titleEn: 'Diagnosis', order: 3 },
    { key: 'treatment', title: '치료', titleEn: 'Treatment', order: 4 },
  ],

  fields: [
    // History
    {
      key: 'chiefComplaint',
      label: '주소',
      labelEn: 'Chief Complaint',
      type: 'text',
      required: true,
      section: 'history',
      order: 1,
      placeholder: '예: 시력저하, 눈 충혈',
      placeholderEn: 'e.g., Vision loss, eye redness',
    },
    {
      key: 'laterality',
      label: '이환 눈',
      labelEn: 'Laterality',
      type: 'select',
      required: true,
      section: 'history',
      order: 2,
      options: [
        { value: 'od', label: 'OD (우안)', labelEn: 'OD (Right Eye)' },
        { value: 'os', label: 'OS (좌안)', labelEn: 'OS (Left Eye)' },
        { value: 'ou', label: 'OU (양안)', labelEn: 'OU (Both Eyes)' },
      ],
    },
    {
      key: 'duration',
      label: '증상 기간',
      labelEn: 'Duration',
      type: 'text',
      required: false,
      section: 'history',
      order: 3,
    },
    {
      key: 'onsetType',
      label: '발생 양상',
      labelEn: 'Onset Type',
      type: 'select',
      required: false,
      section: 'history',
      order: 4,
      options: [
        { value: 'sudden', label: '급성', labelEn: 'Sudden' },
        { value: 'gradual', label: '서서히', labelEn: 'Gradual' },
        { value: 'intermittent', label: '간헐적', labelEn: 'Intermittent' },
      ],
    },
    {
      key: 'associatedSymptoms',
      label: '동반 증상',
      labelEn: 'Associated Symptoms',
      type: 'multiselect',
      required: false,
      section: 'history',
      order: 5,
      options: [
        { value: 'pain', label: '통증', labelEn: 'Pain' },
        { value: 'photophobia', label: '눈부심', labelEn: 'Photophobia' },
        { value: 'tearing', label: '눈물', labelEn: 'Tearing' },
        { value: 'discharge', label: '분비물', labelEn: 'Discharge' },
        { value: 'floaters', label: '비문증', labelEn: 'Floaters' },
        { value: 'flashes', label: '광시증', labelEn: 'Flashes' },
        { value: 'diplopia', label: '복시', labelEn: 'Diplopia' },
        { value: 'halos', label: '달무리', labelEn: 'Halos' },
      ],
    },
    {
      key: 'ocularHistory',
      label: '안과 병력',
      labelEn: 'Ocular History',
      type: 'textarea',
      required: false,
      section: 'history',
      order: 6,
      placeholder: '이전 안과 질환, 수술력',
      placeholderEn: 'Previous ocular diseases, surgeries',
    },
    {
      key: 'systemicHistory',
      label: '전신 병력',
      labelEn: 'Systemic History',
      type: 'textarea',
      required: false,
      section: 'history',
      order: 7,
      placeholder: 'DM, HTN, 자가면역질환 등',
      placeholderEn: 'DM, HTN, autoimmune diseases, etc.',
    },
    {
      key: 'medications',
      label: '안약/약물',
      labelEn: 'Medications',
      type: 'textarea',
      required: false,
      section: 'history',
      order: 8,
    },

    // Examination
    {
      key: 'vaOdUncorrected',
      label: 'VA OD (나안)',
      labelEn: 'VA OD Uncorrected',
      type: 'text',
      required: false,
      section: 'examination',
      order: 1,
      placeholder: '예: 20/40',
      placeholderEn: 'e.g., 20/40',
    },
    {
      key: 'vaOsUncorrected',
      label: 'VA OS (나안)',
      labelEn: 'VA OS Uncorrected',
      type: 'text',
      required: false,
      section: 'examination',
      order: 2,
      placeholder: '예: 20/30',
      placeholderEn: 'e.g., 20/30',
    },
    {
      key: 'vaOdCorrected',
      label: 'VA OD (교정)',
      labelEn: 'VA OD Corrected',
      type: 'text',
      required: false,
      section: 'examination',
      order: 3,
      placeholder: '예: 20/20',
      placeholderEn: 'e.g., 20/20',
    },
    {
      key: 'vaOsCorrected',
      label: 'VA OS (교정)',
      labelEn: 'VA OS Corrected',
      type: 'text',
      required: false,
      section: 'examination',
      order: 4,
      placeholder: '예: 20/20',
      placeholderEn: 'e.g., 20/20',
    },
    {
      key: 'refractionOd',
      label: '굴절검사 OD',
      labelEn: 'Refraction OD',
      type: 'text',
      required: false,
      section: 'examination',
      order: 5,
      placeholder: '예: -2.50 -1.00 x 180',
      placeholderEn: 'e.g., -2.50 -1.00 x 180',
    },
    {
      key: 'refractionOs',
      label: '굴절검사 OS',
      labelEn: 'Refraction OS',
      type: 'text',
      required: false,
      section: 'examination',
      order: 6,
    },
    {
      key: 'iopOd',
      label: 'IOP OD',
      labelEn: 'IOP OD',
      type: 'text',
      required: false,
      section: 'examination',
      order: 7,
      placeholder: '예: 15 mmHg',
      placeholderEn: 'e.g., 15 mmHg',
    },
    {
      key: 'iopOs',
      label: 'IOP OS',
      labelEn: 'IOP OS',
      type: 'text',
      required: false,
      section: 'examination',
      order: 8,
      placeholder: '예: 16 mmHg',
      placeholderEn: 'e.g., 16 mmHg',
    },
    {
      key: 'pupilOd',
      label: '동공 OD',
      labelEn: 'Pupil OD',
      type: 'text',
      required: false,
      section: 'examination',
      order: 9,
      placeholder: 'RAPD 유무, 크기, 반응',
      placeholderEn: 'RAPD, size, reaction',
    },
    {
      key: 'pupilOs',
      label: '동공 OS',
      labelEn: 'Pupil OS',
      type: 'text',
      required: false,
      section: 'examination',
      order: 10,
    },
    {
      key: 'eomOd',
      label: 'EOM OD',
      labelEn: 'Extraocular Movement OD',
      type: 'text',
      required: false,
      section: 'examination',
      order: 11,
      placeholder: 'Full 또는 제한 소견',
      placeholderEn: 'Full or restriction findings',
    },
    {
      key: 'eomOs',
      label: 'EOM OS',
      labelEn: 'Extraocular Movement OS',
      type: 'text',
      required: false,
      section: 'examination',
      order: 12,
    },
    {
      key: 'externalOd',
      label: '외안부 OD',
      labelEn: 'External OD',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 13,
      placeholder: '안검, 눈물길, 결막',
      placeholderEn: 'Eyelids, lacrimal, conjunctiva',
    },
    {
      key: 'externalOs',
      label: '외안부 OS',
      labelEn: 'External OS',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 14,
    },
    {
      key: 'slitLampOd',
      label: '세극등 OD',
      labelEn: 'Slit Lamp OD',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 15,
      placeholder: '각막, 전방, 홍채, 수정체',
      placeholderEn: 'Cornea, anterior chamber, iris, lens',
    },
    {
      key: 'slitLampOs',
      label: '세극등 OS',
      labelEn: 'Slit Lamp OS',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 16,
    },
    {
      key: 'fundusOd',
      label: '안저 OD',
      labelEn: 'Fundus OD',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 17,
      placeholder: '시신경유두, 망막, 황반, 혈관',
      placeholderEn: 'Optic disc, retina, macula, vessels',
    },
    {
      key: 'fundusOs',
      label: '안저 OS',
      labelEn: 'Fundus OS',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 18,
    },
    {
      key: 'gonioscopy',
      label: '전방각경검사',
      labelEn: 'Gonioscopy',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 19,
    },
    {
      key: 'oct',
      label: 'OCT',
      labelEn: 'Optical Coherence Tomography',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 20,
    },
    {
      key: 'visualField',
      label: '시야검사',
      labelEn: 'Visual Field',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 21,
    },
    {
      key: 'fundusPhoto',
      label: '안저사진',
      labelEn: 'Fundus Photo',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 22,
    },
    {
      key: 'ffa',
      label: '형광안저조영술',
      labelEn: 'FFA',
      type: 'textarea',
      required: false,
      section: 'examination',
      order: 23,
    },

    // Diagnosis
    {
      key: 'diagnosisOd',
      label: '진단 OD',
      labelEn: 'Diagnosis OD',
      type: 'textarea',
      required: false,
      section: 'diagnosis',
      order: 1,
    },
    {
      key: 'diagnosisOs',
      label: '진단 OS',
      labelEn: 'Diagnosis OS',
      type: 'textarea',
      required: false,
      section: 'diagnosis',
      order: 2,
    },
    {
      key: 'differentialDiagnosis',
      label: '감별 진단',
      labelEn: 'Differential Diagnosis',
      type: 'textarea',
      required: false,
      section: 'diagnosis',
      order: 3,
    },

    // Treatment
    {
      key: 'medicalTreatment',
      label: '약물 치료',
      labelEn: 'Medical Treatment',
      type: 'textarea',
      required: false,
      section: 'treatment',
      order: 1,
      placeholder: '안약, 경구약',
      placeholderEn: 'Eye drops, oral medication',
    },
    {
      key: 'surgicalTreatment',
      label: '수술적 치료',
      labelEn: 'Surgical Treatment',
      type: 'textarea',
      required: false,
      section: 'treatment',
      order: 2,
    },
    {
      key: 'laserTreatment',
      label: '레이저 치료',
      labelEn: 'Laser Treatment',
      type: 'textarea',
      required: false,
      section: 'treatment',
      order: 3,
    },
    {
      key: 'injectionTreatment',
      label: '주사 치료',
      labelEn: 'Intravitreal Injection',
      type: 'textarea',
      required: false,
      section: 'treatment',
      order: 4,
      placeholder: 'Anti-VEGF, 스테로이드 등',
      placeholderEn: 'Anti-VEGF, steroids, etc.',
    },
    {
      key: 'plan',
      label: '향후 계획',
      labelEn: 'Plan',
      type: 'textarea',
      required: false,
      section: 'treatment',
      order: 5,
    },
    {
      key: 'followUp',
      label: '추적 일정',
      labelEn: 'Follow-up',
      type: 'text',
      required: false,
      section: 'treatment',
      order: 6,
    },
  ],

  aiPrompt: `당신은 안과 전문의입니다. 다음 안과 의무기록을 분석하여 구조화된 JSON으로 추출해주세요.

추출할 필드:
- chiefComplaint: 주소
- laterality: 이환 눈 (od/os/ou)
- duration: 증상 기간
- onsetType: 발생 양상 (sudden/gradual/intermittent)
- associatedSymptoms: 동반 증상 배열
- ocularHistory: 안과 병력
- systemicHistory: 전신 병력
- medications: 안약/약물
- vaOdUncorrected, vaOsUncorrected: 나안 시력
- vaOdCorrected, vaOsCorrected: 교정 시력
- refractionOd, refractionOs: 굴절검사
- iopOd, iopOs: 안압
- pupilOd, pupilOs: 동공
- eomOd, eomOs: 안구운동
- externalOd, externalOs: 외안부
- slitLampOd, slitLampOs: 세극등검사
- fundusOd, fundusOs: 안저
- gonioscopy: 전방각경검사
- oct: OCT
- visualField: 시야검사
- fundusPhoto: 안저사진
- ffa: 형광안저조영술
- diagnosisOd, diagnosisOs: 진단
- differentialDiagnosis: 감별 진단
- medicalTreatment: 약물 치료
- surgicalTreatment: 수술적 치료
- laserTreatment: 레이저 치료
- injectionTreatment: 주사 치료
- plan: 향후 계획
- followUp: 추적 일정

해당 정보가 없으면 null로 설정하세요. JSON만 반환하세요.`,
};
